/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-10-26 00:34:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class activity_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1508977955000L));
    _jspx_dependants.put("jar:file:/Users/guoshuai/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HEO/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1508505273000L));
    _jspx_dependants.put("jar:file:/Users/guoshuai/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HEO/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/Users/guoshuai/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HEO/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1429695504000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<!-- Set render engine for 360 browser -->\n");
      out.write("<meta name=\"renderer\" content=\"webkit\">\n");
      out.write("\n");
      out.write("<!-- No Baidu Siteapp-->\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\n");
      out.write("\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"assets/i/favicon.png\">\n");
      out.write("\n");
      out.write("<!-- Add to homescreen for Chrome on Android -->\n");
      out.write("<meta name=\"mobile-web-app-capable\" content=\"yes\">\n");
      out.write("<link rel=\"icon\" sizes=\"192x192\" href=\"assets/i/app-icon72x72@2x.png\">\n");
      out.write("\n");
      out.write("<!-- Add to homescreen for Safari on iOS -->\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\n");
      out.write("<meta name=\"apple-mobile-web-app-title\" content=\"Amaze UI\" />\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\"\n");
      out.write("\thref=\"assets/i/app-icon72x72@2x.png\">\n");
      out.write("\n");
      out.write("<!-- Tile icon for Win8 (144x144 + tile color) -->\n");
      out.write("<meta name=\"msapplication-TileImage\"\n");
      out.write("\tcontent=\"assets/i/app-icon72x72@2x.png\">\n");
      out.write("<meta name=\"msapplication-TileColor\" content=\"#0e90d2\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./assets/css/amazeui.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./assets/css/amazeui.min.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"./assets/css/amazeui.datatables.min.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/app.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/public.css\">\n");
      out.write("\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<header class=\"am-topbar am-topbar-fixed-top wos-header\">\n");
      out.write("\t<div class=\"am-container\">\n");
      out.write("\t\t<h1 class=\"am-topbar-brand\">\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/WEB-INF/views/home.jsp\">互助</a>\n");
      out.write("\t\t</h1>\n");
      out.write("\n");
      out.write("\t\t<button\n");
      out.write("\t\t\tclass=\"am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-warning am-show-sm-only\"\n");
      out.write("\t\t\tdata-am-collapse=\"{target: '#collapse-head'}\">\n");
      out.write("\t\t\t<span class=\"am-sr-only\">导航切换</span> <span class=\"am-icon-bars\"></span>\n");
      out.write("\t\t</button>\n");
      out.write("\n");
      out.write("\t\t<div class=\"am-collapse am-topbar-collapse\" id=\"collapse-head\">\n");
      out.write("\t\t\t<ul class=\"am-nav am-nav-pills am-topbar-nav\">\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home.jsp\">首页</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"information.jsp\">今日资讯</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/diary.jsp\">专栏</a></li>\n");
      out.write("\t\t\t\t<li class=\"am-dropdown\" data-am-dropdown><a\n");
      out.write("\t\t\t\t\tclass=\"am-dropdown-toggle\" data-am-dropdown-toggle\n");
      out.write("\t\t\t\t\thref=\"javascript:;\"> 案例 <span class=\"am-icon-caret-down\"></span>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<ul class=\"am-dropdown-content\">\n");
      out.write("\t\t\t\t\t\t<li class=\"am-dropdown-header\">案例</li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">1. 游戏案例</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">2. 营销案例</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">3. 工具案例</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"cases.html\">4. 全部案例</a></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t<li><a href=\"profile.html\">评测</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/activity.jsp\">活动</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"am-topbar-right\">\n");
      out.write("\t\t\t\t<button class=\"am-btn am-btn-danger am-topbar-btn am-btn-sm\"\n");
      out.write("\t\t\t\t\tdata-am-offcanvas=\"{target: '#myside',effect: 'push'}\">\n");
      out.write("\t\t\t\t\t<span class=\"am-icon-home am-icon-sm\"></span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- 侧边栏内容 -->\n");
      out.write("\t<div id=\"myside\" class=\"am-offcanvas\">\n");
      out.write("\t\t<div class=\"am-offcanvas-bar am-offcanvas-bar-flip\">\n");
      out.write("\t\t\t<div class=\"am-offcanvas-content\">\n");
      out.write("\t\t\t\t<div class=\"am-g login-face-center\">\n");
      out.write("\t\t\t\t\t<img class=\"am-circle am-img-thumbnail\"\n");
      out.write("\t\t\t\t\t\tsrc=\"http://s.amazeui.org/media/i/demos/bw-2014-06-19.jpg?imageView/1/w/1000/h/1000/q/80\"\n");
      out.write("\t\t\t\t\t\twidth=\"140\" height=\"140\" style=\"text-align: center;\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"am-g\">\n");
      out.write("\t\t\t\t\t<ul class=\"am-nav side_content\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp\">登录</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register.do\">注册</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">消息</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"am-nav-divider\"></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">我的动态</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">设置</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!--[if (gte IE 9)|!(IE)]><!-->\n");
      out.write("\t<script src=\"./assets/js/jquery.min.js\"></script>\n");
      out.write("\t<!--<![endif]-->\n");
      out.write("\t<!--[if lte IE 8 ]>\n");
      out.write("<script src=\"http://libs.baidu.com/jquery/1.11.3/jquery.min.js\"></script>\n");
      out.write("<script src=\"http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js\"></script>\n");
      out.write("<script src=\"assets/js/amazeui.ie8polyfill.min.js\"></script>\n");
      out.write("<![endif]-->\n");
      out.write("\t<script src=\"./assets/js/amazeui.min.js\"></script>\n");
      out.write("\t<script src=\"./assets/js/public.js\"></script>\n");
      out.write("\t<script type=\"./assets/js/amazeui.datatables.min.js\"></script>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"am-container\" style=\"margin-top: 10px\">\n");
      out.write("\t<img src=\"images/tad1.png\" class=\"am-img-responsive\" alt=\"\" />\n");
      out.write("</div>\n");
      out.write("<div class=\"star am-container mcenter\">\n");
      out.write("\t<span><img src=\"images/star.png\">即将开始</span>\n");
      out.write("</div>\n");
      out.write("<div class=\"am-container events\">\n");
      out.write("\t<ul data-am-widget=\"gallery\"\n");
      out.write("\t\tclass=\"am-gallery am-avg-sm-1 am-avg-md-2 am-avg-lg-2 am-gallery-bordered\"\n");
      out.write("\t\tdata-am-gallery=\"{  }\">\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t</ul>\n");
      out.write("\t<div class=\"am-fr\"></div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"star am-container mcenter\">\n");
      out.write("\t<span><img src=\"images/star.png\">往期活动</span>\n");
      out.write("</div>\n");
      out.write("<div class=\"am-container\">\n");
      out.write("\t<ul data-am-widget=\"gallery\"\n");
      out.write("\t\tclass=\"am-gallery am-avg-sm-2 am-avg-md-3 am-avg-lg-3 am-gallery-default\"\n");
      out.write("\t\tdata-am-gallery=\"{ pureview: true }\">\n");
      out.write("\t\t<li>\n");
      out.write("\t\t\t<div class=\"am-gallery-item\">\n");
      out.write("\t\t\t\t<a href=\"http://s.amazeui.org/media/i/demos/bing-1.jpg\" class=\"\">\n");
      out.write("\t\t\t\t\t<img src=\"http://s.amazeui.org/media/i/demos/bing-1.jpg\" alt=\"活动标题\" />\n");
      out.write("\t\t\t\t\t<div class=\"events-btn\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"am-btn am-btn-default\">活动回顾</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</li>\n");
      out.write("\t\t<li>\n");
      out.write("\t\t\t<div class=\"am-gallery-item\">\n");
      out.write("\t\t\t\t<a href=\"http://s.amazeui.org/media/i/demos/bing-2.jpg\" class=\"\">\n");
      out.write("\t\t\t\t\t<img src=\"http://s.amazeui.org/media/i/demos/bing-2.jpg\"\n");
      out.write("\t\t\t\t\talt=\"某天 也许会相遇 相遇在这个好地方\" />\n");
      out.write("\t\t\t\t\t<div class=\"events-btn\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"am-btn am-btn-default\">活动回顾</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</li>\n");
      out.write("\t\t<li>\n");
      out.write("\t\t\t<div class=\"am-gallery-item\">\n");
      out.write("\t\t\t\t<a href=\"http://s.amazeui.org/media/i/demos/bing-3.jpg\" class=\"\">\n");
      out.write("\t\t\t\t\t<img src=\"http://s.amazeui.org/media/i/demos/bing-3.jpg\"\n");
      out.write("\t\t\t\t\talt=\"不要太担心 只因为我相信\" />\n");
      out.write("\t\t\t\t\t<div class=\"events-btn\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"am-btn am-btn-default\">活动回顾</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</li>\n");
      out.write("\t\t<li>\n");
      out.write("\t\t\t<div class=\"am-gallery-item\">\n");
      out.write("\t\t\t\t<a href=\"http://s.amazeui.org/media/i/demos/bing-4.jpg\" class=\"\">\n");
      out.write("\t\t\t\t\t<img src=\"http://s.amazeui.org/media/i/demos/bing-4.jpg\"\n");
      out.write("\t\t\t\t\talt=\"终会走过这条遥远的道路\" />\n");
      out.write("\t\t\t\t\t<div class=\"events-btn\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"am-btn am-btn-default\">活动回顾</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</li>\n");
      out.write("\t\t<li>\n");
      out.write("\t\t\t<div class=\"am-gallery-item\">\n");
      out.write("\t\t\t\t<a href=\"http://s.amazeui.org/media/i/demos/bing-3.jpg\" class=\"\">\n");
      out.write("\t\t\t\t\t<img src=\"http://s.amazeui.org/media/i/demos/bing-3.jpg\"\n");
      out.write("\t\t\t\t\talt=\"不要太担心 只因为我相信\" />\n");
      out.write("\t\t\t\t\t<div class=\"events-btn\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"am-btn am-btn-default\">活动回顾</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</li>\n");
      out.write("\t\t<li>\n");
      out.write("\t\t\t<div class=\"am-gallery-item\">\n");
      out.write("\t\t\t\t<a href=\"http://s.amazeui.org/media/i/demos/bing-4.jpg\" class=\"\">\n");
      out.write("\t\t\t\t\t<img src=\"http://s.amazeui.org/media/i/demos/bing-4.jpg\"\n");
      out.write("\t\t\t\t\talt=\"终会走过这条遥远的道路\" />\n");
      out.write("\t\t\t\t\t<div class=\"events-btn\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"am-btn am-btn-default\">活动回顾</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</li>\n");
      out.write("\t</ul>\n");
      out.write("\t<div class=\"am-fr\"></div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("\t<div class=\"content\">\n");
      out.write("\t\t<ul class=\"am-avg-sm-5 am-avg-md-5 am-avg-lg-5 am-thumbnails\">\n");
      out.write("\t\t\t<li><a href=\"#\">联系我们</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">加入我们</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">合作伙伴</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">广告及服务</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">友情链接</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<div class=\"btnlogo\">\n");
      out.write("\t\t\t<img src=\"images/btnlogo.png\" />\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<p>\n");
      out.write("\t\t\tBlack出品<br>© 2016 AllMobilize, Inc. Licensed under MIT license.\n");
      out.write("\t\t\tDeveloped with WebStorm.\n");
      out.write("\t\t</p>\n");
      out.write("\t\t<div class=\"w2div\">\n");
      out.write("\t\t\t<ul data-am-widget=\"gallery\"\n");
      out.write("\t\t\t\tclass=\"am-gallery am-avg-sm-2\n");
      out.write("  am-avg-md-2 am-avg-lg-2 am-gallery-overlay\"\n");
      out.write("\t\t\t\tdata-am-gallery=\"{ pureview: true }\">\n");
      out.write("\t\t\t\t<li class=\"w2\">\n");
      out.write("\t\t\t\t\t<div class=\"am-gallery-item\">\n");
      out.write("\t\t\t\t\t\t<h3 class=\"am-gallery-title\">订阅号：Black</h3>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"w2\">\n");
      out.write("\t\t\t\t\t<div class=\"am-gallery-item\">\n");
      out.write("\t\t\t\t\t\t<a href=\"images/face3.jpg\">\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"am-gallery-title\">服务号：Black</h3>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /activity.jsp(15,2) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(1);
      // /activity.jsp(15,2) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(4);
      // /activity.jsp(15,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("c");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t<li>\n");
            out.write("\t\t\t<div class=\"am-gallery-item\">\n");
            out.write("\t\t\t\t<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/activity_show.jsp\" class=\"\">\n");
            out.write("\t\t\t\t\t<img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/images/bb1.jpg\" alt=\"活动标题\" />\n");
            out.write("\t\t\t\t\t<div class=\"efe\">活动标题</div>\n");
            out.write("\t\t\t\t\t<p>活动简介活动简介活动简介活动简介活动简介活动简介活动简介活动简介活动简介活动简介</p>\n");
            out.write("\t\t\t\t\t<div class=\"am-gallery-desc fee\">\n");
            out.write("\t\t\t\t\t\t<div class=\"am-fl\">大连</div>\n");
            out.write("\t\t\t\t\t\t<div class=\"am-fr\">2017-10-20</div>\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t</a>\n");
            out.write("\t\t\t</div>\n");
            out.write("\t\t</li>\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
